<?php

use function Deployer\add;
use function Deployer\after;
use Deployer\BaseLaravelDeployDriver;
use function Deployer\run;
use function Deployer\task;
use Deployer\Tasks\CopyUpdatableToShare;
use Deployer\Tasks\GitInit;

require 'php-deployer/BaseLaravelDeployDriver.php';

class TeraceptionApplicationDashboardDeployer extends BaseLaravelDeployDriver{
    public function __construct()
    {
        parent::__construct();
        $this->hostname = "teraception-web";
        $this->repo = "ssh://Talha5389@bitbucket.org/teraception/teraception-application-dashboard-web";
        $this->envFile = ".env";
        $this->localAssetsPath = "deployment";
        $this->webUser = "www-data";
        $this->sshConfigFile = "c:/Users/talha/.ssh/config";
        $this->deployPath = "/disk-drive-1/www/application_dashboard";
        $this->httpVhostFile = "application-dashboard.conf";
        //$this->sslVhostFile = "002-application-dashboard-443.conf";
        $this->hostuser = "azureuser";
    }

    public function initTasks()
    {
        parent::initTasks(); // TODO: Change the autogenerated stub
        $this->tasks['npm:init'] = new \Deployer\Tasks\NPMInit();
        $gTask = new GitInit();
        $gTask->addUrlAlias("https://bitbucket.org/code5389/php-deployer.git","ssh://Talha5389@bitbucket.org/code5389/php-deployer.git");
        $this->tasks['git:config:init'] = $gTask;
        $cTask = new CopyUpdatableToShare();
        $cTask->to_copy = [
            '.env'
        ];
        $this->tasks['copy:shared_updatable'] = $cTask;
    }

    public function registerTasks()
    {
        parent::registerTasks(); // TODO: Change the autogenerated stub
        task('apidoc:init',function (){
            run('npm install -g apidoc');
            run('apidoc -i {{release_path}}/app -o {{release_path}}/public/apidoc');
        });
    }

    public function registerAfter()
    {
        parent::registerAfter(); // TODO: Change the autogenerated stub
        after('npm:init','apidoc:init');
    }
}

$deployDriver = new TeraceptionApplicationDashboardDeployer();
$deployDriver->run();