<?php

namespace App\Custom;
use Illuminate\Http\Request;
use Illuminate\Routing\RouteCollection;

/**
 * Created by PhpStorm.
 * User: talha
 * Date: 7/6/2017
 * Time: 2:06 PM
 */
class CustomUrlGenerator extends \Illuminate\Routing\UrlGenerator
{
    protected $localeParameterName;
    protected $generateLocalized;

    public function currentRoute($parameters = []){
        $route = $this->request->route()->getName();
        $preParameters = $this->request->route()->parameters();
        $query = $this->request->query();
        $preParameters = array_merge($query,$preParameters);
        foreach ($parameters as $name => $val){
            $preParameters[$name] = $val;
        }

        return $this->route($route,$preParameters);
    }

    public function __construct(RouteCollection $routes, Request $request)
    {
        $this->localeParameterName = config('app.locale_parameter_name');
        $this->generateLocalized = config('app.generate_localized_urls');
        parent::__construct($routes, $request);
    }

    public function formatParameters($parameters)
    {
        $p = parent::formatParameters($parameters); // TODO: Change the autogenerated stub

        if($this->generateLocalized && !empty($this->localeParameterName) && !isset($p[$this->localeParameterName])){
            $p[$this->localeParameterName] = app()->getLocale();
        }

        return $p;
    }
}